### ISSUE TITLE
[Birthday] Error when issuing "bday list" in a DM

### ISSUE THREAD

**Issue by ajwsert** [ZeLarpMaster/ZeCogsV3#24]
Apparently `bday list` isn't supposed to work with DM? This error is thrown in console when using it in a DM:
```
Exception in command 'bday list'
Traceback (most recent call last):
....
  File ".../cogs/birthdays/birthdays.py", line 131, in bday_list
    bdays = await self.get_guild_date_configs(message.guild.id)
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 ...
  File ".../site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by ZeLarpMaster** [comment]
Should be fixed in the newest version. My cogs weren't up to date with the newest version of RedBotV3 and there were some breaking changes.

Please close this if it's indeed fixed.

**Comment by ZeLarpMaster** [comment]
No news for a while, assuming it's fixed. If not, reopen or make another one.
