### ISSUE TITLE
react_roles traceback

### ISSUE THREAD

**Issue by DirtyCajunRice** [ZeLarpMaster/ZeCogsV3#29]
```
Traceback (most recent call last):
 File "/root/.local/share/VarkenBot/cogs/CogManager/cogs/react_roles/react_roles.py", line 141, in _init_bot_manipulation
 msg = await self.safe_get_message(channel, msg_id)
File "/root/.local/share/VarkenBot/cogs/CogManager/cogs/react_roles/react_roles.py", line 493, in safe_get_message
result = await channel.get_message(message_id)
AttributeError: 'TextChannel' object has no attribute 'get_message'
```

**Comment by ZeLarpMaster** [comment]
Should be fixed in the latest version of the cog, thanks for the report!
