### ISSUE TITLE
[birthdays] no announcement

### ISSUE THREAD

**Issue by theMisteryDE** [ZeLarpMaster/ZeCogsV3#42]
Welp, like I already said in the last commit, after the update there where no announcement.
For the Logs:
-- Logs begin at Wed 2020-09-23 18:06:59 UTC, end at Wed 2020-10-21 14:00:45 UTC. --
-- No entries --

To be honest, this was the first birthday in October, so I can't say since when the Problem is occuring. Birthday on September 29th was announced. My Bot updates daily with scheduler, so maybe an issue from Update at October 6th?

**Comment by theMisteryDE** [comment]
And again. While an birthday at November 11th was announced, another birthday today wasn't.
It kinda starts like Tobo's streamroles, random announcements.

**Comment by Menteroth** [comment]
It didn't announce my birthday today for whatever reason. Well hasn't yet anyway.
Last year it announced at 1 AM.

**Comment by Menteroth** [comment]
Just found this at startup.

```Unhandled exception in internal background task 'bdaytask'.
Traceback (most recent call last):
  File "c:\__\coding\redenv\lib\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "C:\__\coding\Soundwave\cogs\CogManager\cogs\bday\bday.py", line 55, in bdaytask
    role := member.guild.get_roles(
AttributeError: 'Guild' object has no attribute 'get_roles'
```

**Comment by theMisteryDE** [comment]
today is my birthday, no announcement aswell.
